version: "3.9"
services:
  web:
    image: rschellenberg/nodejs
    container_name: ppsre-app-ecr-repo
    env_file: .env
    restart: always
    build:
      context: .
      dockerfile: dockerfile
    command:
      node node.js
    ports:
      - "80:80"
    networks:
      - web_network
    volumes:
       - appdata:/app
  
networks:
  web_network:
    driver: bridge

volumes:
  appdata:
   driver: local
